#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()
count = 0
for i in lines:
    if i.startswith( "@" ):
    # filters out lines starting with t_id
        continue
    fields = i.split("\t")
    if fields[2] == "2L":
        if 10000 <= float(fields[3]) <= 20000:
            count += 1

print count
