#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()
count = 0
for i in lines:
    if i.startswith( "@" ):
    # filters out lines starting with t_id
        continue
    fields = i.split("\t")
    if count < 10:        
    #Start and end are in columns 3 and 4
       count += 1
       print fields[2]
     
       
            

    
