#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()
count = 0
for i in lines:
    if i.startswith( "@" ):
    # filters out lines starting with t_id
        continue
    count += 1
    
print count
