#!/usr/bin/env python

"""
Converting .tsv to .FASTA
./01-tsv_to_fasta <filename.tsv>
"""


import sys


file = open(sys.argv[1])



for i in file:
    fields = i.rstrip("\t\n").split("\t")
    print ">" + fields[0] + "\n" + fields[1].replace("-","")
    








