#!/usr/bin/env python

"""
Reads a peptide sequence and puts the nucleotide sequence from a .fasta file. Puts three -'s for every blank in the peptide
./02-peptide_to_nucleotide <homolog.fa> <peptide_alignment.fa>
"""


import sys
import fasta


nucleotide = open(sys.argv[1])
peptide = open(sys.argv[2])


peptide_sequence = []
fasta_identifier = []

for ident, sequences in fasta.FASTAReader( peptide ):
    peptide_sequence.append(sequences)
    fasta_identifier.append(ident)
    


nucleotide_sequence = []

for ident, sequences in fasta.FASTAReader( nucleotide ):
    nucleotide_sequence.append(sequences)      
    
    


for i in range(len(peptide_sequence)):
    codon_pos = 0
    new_seq = "" 
    print ">" + fasta_identifier[i]
    for p in peptide_sequence[i]:
        if p == "-":
            new_seq += "---"
        else:
            new_seq += nucleotide_sequence[i][codon_pos:codon_pos+3]
            codon_pos += 3
    print new_seq
            

    
        



    

        

