#!/usr/bin/env python

import sys

total = 0
count = 0

for i in sys.stdin:
    if sys.argv[-1] == "-a":
        i = i.rstrip()
        total += int(i)
        count += 1

if sys.argv[-1] == "-a":
    print total/count